config/routes.rb
Rails.application.routes.draw do
  get 'profiles/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/myapplications', to: 'pages#myapplications', as: :myapplications
  resources :positions,   only: [:create, :update, :show]
  resources :team,        only: [:create, :update]
  resources :walks,       only: [:create, :update, :destroy, :index, :show, :new] do
    resources :user_walks,  only: [:create]
  end
  resources :user_walks, only: [:destroy, :edit, :update]
  resources :skill_sets,  only: [:create, :update, :destroy]
  resources :skills,      only: [:create, :update]
  resources :profiles, only: [:update]
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
  belongs_to :skillable, polymorphic: true
  belongs_to :skill

  validates :skill, presence: true
  validates :level, presence: true
end

app/controllers/skill_sets_controller.rb
class SkillSetsController < ApplicationController
  before_action :set_skill_set, only: [:destroy]

  def create
    @skill_set = SkillSet.new(skill_set_params)
    configure_skillable(@skill_set)

    authorize @skill_set

    if @skill_set.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :'pages/dashboard' }
        format.js
      end
    end
  end

  def update
  end

  def destroy
    @skill_set.destroy
    @empty_skill_set = current_user.skill_sets.where(level: @skill_set.level, skillable_type: @skill_set.skillable_type).empty?
  end

  private

  def set_skill_set
    @skill_set = SkillSet.find(params[:id])
    authorize @skill_set
  end

  def skill_set_params
    params.require(:skill_set).permit(:skill_id, :level, :skillable_type)
  end

  def configure_skillable(skill_set)
    case skill_set.skillable_type
    when "Position"
      skill_set.skillable = current_user.current_positions.first
    when "User"
      skill_set.skillable = current_user
    end
  end
end

app/views/skill_sets/_form.html.erb
<%= simple_form_for skill_set, method: :post, remote: true, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
  <%= f.association :skill, label_method: :name, value_method: :id, include_blank: "Select skill", wrapper_html: { class: 'form-group' } %>
  <% if skillable_type == "Position" %>
    <%= f.input :level, collection: { "Master" => 3, "Comfortable with" => 2, "Notions" => 1 }, include_blank: "Select level",  wrapper_html: { class: 'form-group' } %>
  <% else %>
    <%= f.input :level, input_html: { value: 3 }, as: :hidden %>
  <% end %>
  <%= f.input :skillable_type, input_html: { value: skillable_type }, as: :hidden %>
  <%= f.submit 'Add', class: 'btn-apply' %>
<% end %>

app/views/skill_sets/_show.html.erb
<div class="skill-card" data-skill-set-id="<%= skill_set.id %>">
  <div class="skill-card-name"><p><%= skill_set.skill.name.capitalize %></p></div>
  <%=link_to skill_set_path(skill_set), method: :delete, remote: true do %>
  <div class="skill-card-delete"><i class="fas fa-times"></i></div>
  <% end %>
</div>

app/views/skill_sets/create.js.erb
function initializeForm() {
  let newSkillForm = "";
  const skillable_type = '<%= @skill_set.skillable_type %>';
  if (skillable_type === "Position") {
    newSkillForm = document.getElementById('position-skill-form');
  } else if (skillable_type === "User"){
    newSkillForm = document.getElementById('user-skill-form');
  }
  return newSkillForm;
};

function refreshForm(form, skillFormHTML) {
  form.innerHTML = skillFormHTML;
}

function hideForm(form) {
  form.parentNode.style.display = "none";
}

function addSkillSet(skillShowHTML) {
  const skillContainer = document.getElementById('<%=@skill_set.skillable_type.downcase%>-skills-<%=@skill_set.level%>-container');
  skillContainer.insertAdjacentHTML('beforeend', skillShowHTML);
  const emptySkill = skillContainer.querySelector(".empty-skill");
  if(emptySkill) {
    emptySkill.style.display = "none";
  }
}

function showNewButton(form) {
  form.parentNode.previousElementSibling.style.display = "block";
}

<% if @skill_set.errors.any? %>
  refreshForm(initializeForm(), '<%= j render "skill_sets/form", skill_set: @skill_set, skillable_type: @skill_set.skillable_type %>');
<% else %>
  addSkillSet('<%= j render "skill_sets/show", skill_set: @skill_set %>');
  refreshForm(initializeForm(), '<%= j render "skill_sets/form", skill_set: SkillSet.new, skillable_type: @skill_set.skillable_type %>');
  hideForm(initializeForm());
  showNewButton(initializeForm());
<% end %>

app/views/skill_sets/destroy.js.erb
function destroySkillSet() {

  document.querySelector("[data-skill-set-id='<%= @skill_set.id %>']").remove();
  console.log("<%=@empty_skill_set%>");
  <% if @empty_skill_set %>
    console.log("hello");
    const skillContainer = document.getElementById('<%=@skill_set.skillable_type.downcase%>-skills-<%=@skill_set.level%>-container');
    const emptySkill = skillContainer.querySelector(".empty-skill");
    if(emptySkill) {
      emptySkill.style.display = "block";
    }
  <% end %>

}

destroySkillSet();