config/routes.rb
Rails.application.routes.draw do
  get 'profiles/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/myapplications', to: 'pages#myapplications', as: :myapplications
  resources :positions,   only: [:create, :update, :show]
  resources :team,        only: [:create, :update]
  resources :walks,       only: [:create, :update, :destroy, :index, :show, :new] do
    resources :user_walks,  only: [:create]
  end
  resources :user_walks, only: [:destroy, :edit, :update]
  resources :skill_sets,  only: [:create, :update, :destroy]
  resources :skills,      only: [:create, :update]
  resources :profiles, only: [:update]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2019 The Wim Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">

    <div class="d-flex align-items-center">
      <div class="navbar-icon mr-2"></div>
      <h2><%= link_to "WalkInMy.Team", root_path %> </h2>
    </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# unless current_user.positions.where(role: "manager").empty? %>
          <!-- <li class="nav-item pt-3">
            <strong> <%#= link_to "Manage walks", new_walk_path, class: "nav-link" %> </strong>
          </li> -->
        <%# end %>
        <li class="nav-item pt-3 walks_index">
          <h5> <%= link_to dashboard_path, class: "nav-link" do %> <i class="fas fa-rocket mr-2"></i>Find a walk<% end %></h5>
        </li>
        <li class="nav-item pt-3 pages_myapplications">
          <h5> <%= link_to myapplications_path, class: "nav-link" do %><i class="fab fa-wpforms mr-2"></i>My dashboard<% end %></h5>
        </li>
        <!-- <li class="nav-item pt-3 pages_dashboard">
          <h5> <%= link_to dashboard_path, class: "nav-link" do %> <i class="fas fa-user mr-2"></i>My profile<% end %></h5>
        </li> -->
        <li class="nav-item pt-3">
          <h5> <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %> </h5>
        </li>
       <!-- <li class="nav-item pt-3">
        <div class="avatar">
          <div class="avatar-mine" style="background-image: url(<%= cl_image_path current_user.photo.key %>);">
          </div>
        </li> -->
      <% else %>
        <li class="nav-item pt-3">
          <h5> <%= link_to "Login", new_user_session_path, class: "nav-link" %> </h5>
        </li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <div class="avatar pl-2">
        <div class="avatar-mine" style="background-image: url(<%= cl_image_path current_user.photo.key, gravity: :face, width: 40 , height: 40, crop: :thumb; %>)">
        </div>
      </div>
    <% end %>
  </div>
</div>