config/routes.rb
Rails.application.routes.draw do
  get 'profiles/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/myapplications', to: 'pages#myapplications', as: :myapplications
  resources :positions,   only: [:create, :update, :show]
  resources :team,        only: [:create, :update]
  resources :walks,       only: [:create, :update, :destroy, :index, :show, :new] do
    resources :user_walks,  only: [:create]
  end
  resources :user_walks, only: [:destroy, :edit, :update]
  resources :skill_sets,  only: [:create, :update, :destroy]
  resources :skills,      only: [:create, :update]
  resources :profiles, only: [:update]
end

app/views/pages/_new_user_skillset_form.html.erb
<%= simple_form_for([ skill_set ], remote: true) do |form| %>
  <%= form.input :name %>
  <%= form.button :submit %>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="tab-content" id="pills-tabContent">
    <!-- Tab d'index des walks -->
    <div class="tab-pane fade" id="find" role="tabpanel" aria-labelledby="find-tab">
      <!-- Contenu -->
    </div>

    <!-- Tab des applications -->
    <div class="tab-pane fade" id="applications" role="tabpanel" aria-labelledby="applications-tab">
      <!-- Contenu -->
    </div>

    <!-- Tab de profile -->
    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="d-flex justify-content-center flex-wrap mt-5">

        <!-- Profile -->
        <div class="card w-70">
          <div class="profile-card" data-user-id="<%= current_user.id %>">
            <div class="profile-picture">
              <%= cl_image_tag current_user.photo.key, height: 150, width: 150, crop: :fill, gravity: :face %>
            </div>
            <div class="profile-info">
              <div><h1><%= current_user.first_name %> <%= current_user.last_name %></h1></div>
              <div class="d-flex">
                  <p><i class="fas fa-envelope mr-1"></i> <%= current_user.email %></p>
                  <p><i class="fas fa-users mr-1"></i> <%= current_user.current_teams.first.name %></p>
                  <p><i class="fas fa-graduation-cap mr-1"></i> <%= current_user.experience %> year(s)</p>
              </div>

                <div class="search-toggle mb-2">

                  <div class="toggle-color d-flex">
                    <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="top" data-content="Looking for a <strong>discovery</strong> walk" data-html="true">
                      <span class="mr-1 rocket <%= current_user.purpose == "Discovery" ? 'checked-icon' : '' %>"><i class="fas fa-rocket mr-1"></i></span>
                    </span>
                    <ul class="tg-list">
                      <li class="tg-list-item">
                      <input class="tgl tgl-flat" id="cb4" type="checkbox" <%= current_user.purpose == "Recruitment" ? 'checked' : '' %>/>
                      <label class="tgl-btn" for="cb4"></label>
                      <input id="toggle-authenticity-token" value="<%= form_authenticity_token %>" type="hidden" />
                      </li>
                    </ul>
                    <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="top" data-content="Looking for a <strong>recruitment</strong> walk" data-html="true">
                      <span class="ml-1 handshake <%= current_user.purpose == "Recruitment" ? 'checked-icon' : '' %>"><i class="fas far fa-handshake ml-1"></i></span>
                    </span>
                  </div>
                </div>

              <div class="profile-description">
                <em><%= current_user.description %></em>
            </div>
            </div>
          </div>
        </div>

          <!-- -------------- -->
          <!-- Current skills -->
          <!-- -------------- -->
          <div class="card w-70 skills-card accordion mt-2" id="accordionExample2">

            <div class="d-flex justify-content-between collapse-header" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
              <h2 class="m-0"><i class="fa fa-check-circle mr-3"></i>Current skills</h2>
              <div class="expand-notice"><i class="fas fa-chevron-down"></i></div>
            </div>

            <div id="collapseTwo" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample2">

              <!-- I perfectly master -->
              <div class="mb-2">
                <h2 class="level-title">I perfectly master</h2>
                <div id="position-skills-3-container">
                  <% if current_user.current_positions.first.top_skill_sets.empty? %>
                    <p class="empty-skill">You have not entered any skill yet !</p>
                  <% end %>
                  <% current_user.current_positions.first.top_skill_sets.each do |skill_set| %>
                    <%= render 'skill_sets/show', skill_set: skill_set %>
                  <% end %>
                </div>
              </div>

              <!-- I am comfortable with -->
              <div class="mb-2">
                <h2 class="level-title">I am comfortable with</h2>
                <div id="position-skills-2-container">
                  <% if current_user.current_positions.first.medium_skill_sets.empty? %>
                    <p class="empty-skill">You have not entered any skill yet !</p>
                  <% end %>
                  <% current_user.current_positions.first.medium_skill_sets.each do |skill_set| %>
                    <%= render 'skill_sets/show', skill_set: skill_set %>
                  <% end %>
                </div>
              </div>

              <!-- I have notions -->
              <div class="mb-2">
                <h2 class="level-title">I have notions</h2>
                <div id="position-skills-1-container">
                  <% if current_user.current_positions.first.low_skill_sets.empty? %>
                    <p class="empty-skill">You have not entered any skill yet !</p>
                  <% end %>
                  <% current_user.current_positions.first.low_skill_sets.each do |skill_set| %>
                    <%= render 'skill_sets/show', skill_set: skill_set %>
                  <% end %>
                </div>
              </div>

              <!-- Add new skill -->
              <div class="skill-new-container">
                <div class="skill-new"><i class="fas fa-plus"></i> Add new skill</div>
                <div class="skill-new-form-container">
                  <div id="position-skill-form">
                    <%= render 'skill_sets/form', skill_set: @skill_set, skillable_type: "Position" %>
                  </div>
                  <div class="skill-new-cancel"><div class="close-cross"><i class="fas fa-times"></i></div> <div class="close-text">Close</div></div>
                </div>
              </div>

            </div>
          </div>

          <!-- ------------------------ -->
          <!-- Skills I'm interested in -->
          <!-- ------------------------ -->
          <div class="card w-70 skills-card accordion" id="accordionExample3">
            <div class="d-flex justify-content-between collapse-header" id="headingThree"  data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
              <h2 class="m-0"><i class="fas fa-search-plus mr-3"></i>Skills I'm interested in</h2>
              <div class="expand-notice"><i class="fas fa-chevron-down"></i></div>
            </div>

            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample3">

              <!-- Must have skills -->
              <div class="mt-2 mb-2">
                <div id="user-skills-3-container">
                  <% if current_user.top_skill_sets.empty? %>
                  <p class="empty-skill">You have not entered any skill yet !</p>
                  <% end %>
                  <% current_user.top_skill_sets.each do |skill_set| %>
                    <%= render 'skill_sets/show', skill_set: skill_set %>
                  <% end %>
                </div>
              </div>

              <!-- Add new skill -->
              <div class="skill-new-container">
                <div class="skill-new"><i class="fas fa-plus"></i> Add new skill</div>
                  <div class="skill-new-form-container">
                    <div id="user-skill-form">
                      <%= render 'skill_sets/form', skill_set: @skill_set, skillable_type: "User" %>
                    </div>
                  <div class="skill-new-cancel"><div class="close-cross"><i class="fas fa-times"></i></div> <div class="close-text">Close</div></div>
                </div>
              </div>
          </div>
        </div>

        <div class="container w-70">
          <%= link_to walks_path, style: "color: white;" do %>
            <div class="container d-flex justify-content-around mt-3 mb-5 button btn-letswalk">
              Let's walk!
            </div>
          <% end %>
        </div>

          <!-- </div> -->
        </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="align-self-start" id="navbar-home">
  <%= render 'shared/navbar' %>
</div>
<!-- First section : video banner -->
<div class="video-relative" id="video-home">
  <%= video_tag "Office.mp4", autoplay: true, loop: true, muted: true, class: "video" %>
  <!-- <div class="video-absolute-typed">
    <h1><span id="banner-typed-text"></span></h1>
  </div> -->
  <div class="video-absolute-title">
    <h1>Curious? Eager to learn?</br>
    Discover your colleagues across the hall!</h1>
 </div>

  <div class="video-absolute-btn">
    <a href="#pts" class="banner-link"><div class="banner-button btn-apply">Start now !</div></a>
  </div>
</div>

<!-- Second section : Pain Target Solution (id = pst) -->
<div class="container d-flex flex-column justify-content-center align-items-center pt-3" id="pts">
  <div class="text-center">
    <h1>WalkInMy.Team helps you discover new jobs<br/> and connect with your colleagues</h1>
  </div>
  <div class="pts-cards">
    <div class="pts-card">
      <h3>Find</h3>
      <p>Fill-in your profile and let the app suggest a great match!</p>
        <div class="pts-card-image">
        <%= image_tag 'find.png', alt: "find" %>
        </div>
    </div>
    <div class="pts-card">
      <h3>Apply</h3>
      <p>Apply to the walk that best fits your expectations</p>
        <div class="pts-card-image">
        <%= image_tag 'apply.png', alt: "apply" %>
        </div>
    </div>
    <div class="pts-card">
      <h3>Walk!</h3>
      <p>Walk in a new team and learn more about your company!</p>
        <div class="pts-card-image">
        <%= image_tag 'walk.png', alt: "walk" %>
        </div>
    </div>
  </div>
  <div>
    <a href="#walks" class="banner-link"><div class="banner-button btn-apply">Show me more</div></a>
  </div>
</div>

<!-- Intermediary section -->
<div class="banner mb-5">
<!-- class="banner d-flex flex-column justify-content-between align-items-center" id="static-banner" -->
</div>

<!-- Third section : Walks examples (id = walks) -->
<div class="container d-flex flex-column pt-3 mt-5" id="walks">
  <div class="py-4">
  <h2>Our best walks</h2>
  </div>
  <div class="row">
    <% @user_walks.each do |user_walked| %>

      <div class="col cards">
        <%= link_to walk_path(user_walked),:action => 'go' do  %>
        <div class="card-homepage">
          <!-- Walk team picture -->
          <% if user_walked.walk.team.photo.attached?%>

            <%= cl_image_tag user_walked.walk.team.photo.key, width: 400, height: 300, crop: :fill %>
          <% else %>
            <%= cl_image_tag "", width: 400, height: 300, crop: :fill %>
          <% end %>
          <!-- Walk team details -->
          <div class="card-homepage-infos">
            <div>
              <h4><%= user_walked.walk.team.name %> team</h4>
              <p><%= truncate(user_walked.walk.description, :length => 80, :separator => ' ') %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- Fourth section : Testimonies (id = walks) -->
<div class="py-4">
  <h2>Walker reviews</h2>
</div>

  <div class="row ">
    <% @user_walks.each do |user_walked| %>
      <div class="col cards">
        <div class="card">
          <div class="card-info d-flex align-items-center", class="avatar">
            <div style="{width: 85; height: 85;}">
              <% if user_walked.user.photo.attached?%>
                <%= cl_image_tag user_walked.user.photo.key, width: 85, height: 85, crop: :thumb, gravity: :face %>
              <% else %>
                <%= cl_image_tag "", width: 75, height: 75, crop: :fill, class: "rounded-circle mr-4" %>
              <% end %>
            </div>
            <div class="">
              <h4 class="mb-1 mx-2"><%= user_walked.user.first_name %></h4>
              <!-- <div class="card-description p-2"> -->
              <p class="mx-2 mb-1"><i>"<%= truncate(user_walked.review,:length => 60, :separator => ' ') %>"</i></p>
            <!-- </div> -->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

<!-- Call to action : Let's walk -->

  <%= link_to dashboard_path, style: "color: white;" do %>
    <div class="container d-flex justify-content-around my-5 button btn-letswalk">
      Get started!
    </div>
  <% end %>

app/views/pages/myapplications.html.erb
<div class="banner-myapp">
  <h1>My dashboard</h1>
</div>
<div class="container my-3">

  <!-- My applications---------------------------------------->
    <div class="cards-walks">
      <% i=0 %>
      <% @upcoming_user_walks.each do |user_walk| %>
      <div class="card-application card-application-active" data-user-walk-id="<%= user_walk.id %>">
        <%= link_to "", walk_path(user_walk.walk) %>
        <div class="card-application-image">
          <%= cl_image_tag user_walk.walk.team.photo.key, width: 180, height: 180, crop: :fill, gravity: :faces if user_walk.walk.team.photo.attached? %>
        </div>
        <div class="card-application-infos">
          <h2><%= user_walk.walk.title %></h2>
          <h6 class="duration mb-2"><i class="fas fa-calendar-week"></i><%= user_walk.display_start_date %> - <%= user_walk.display_end_date %> </h6>
          <h6 class="duration">
          <% if user_walk.walk.purpose == "Recruitment"%>
            <i class="fas far fa-handshake">
            </i> Recruitment
          <% else %>
            <i class="fas fa-rocket">
            </i> Discovery
          <% end %>
          <i class="ml-3 fas fa-users">
          </i><%= user_walk.walk.team.name %>
          <i class="ml-3 fas fa-thumbtack">
          </i><%= user_walk.walk.team.location %> </h6>
          <p class="ml-0">My message:
          <em>"<%= user_walk.motivation.truncate(67) %>"</em>
          </p>
        </div>
        <div class="myapp-btns">
          <div class="badge badge-primary badge-pill status"><%= user_walk.status %></div>
          <div id=<%= "sweet-alert-delete-#{i}"%> class="btn-details"><i class="fas fa-window-close"></i>  Cancel application</div>
          <% i+=1 %>
          <%= link_to "", user_walk, method: :delete, id: "delete-link", class: "hidden", remote: true %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="cards-walks">
      <% @past_user_walks.each do |user_walk| %>
        <div class="card-application past-application">
          <div class="card-application-image">
            <%= cl_image_tag user_walk.walk.team.photo.key, width: 180, height: 180, crop: :fill, gravity: :faces if user_walk.walk.team.photo.attached? %>
          </div>
        <div class="card-application-infos past-application">
          <h2><%= user_walk.walk.title %></h2>
          <h6 class="duration mb-2"></i><%= user_walk.display_start_date %> - <%= user_walk.display_end_date %> </h6>
          <h6 class="duration">
            <% if user_walk.walk.purpose == "Recruitment"%>
              <i class="fas far fa-handshake">
              </i> Recruitment
            <% else %>
              <i class="fas fa-rocket">
              </i> Discovery
            <% end %>
            <i class="ml-3 fas fa-users"></i>
            <%= user_walk.walk.team.name %>
            <i class="ml-3 fas fa-thumbtack"></i>
            <%= user_walk.walk.team.location %>
          </h6>
          <p class="ml-0">My review:
            <% unless user_walk.review.nil? %>
                <em>"<%= user_walk.review.truncate(67) %>"</em>
            <% end %>
            <span class="review-edit">
              <%= link_to edit_user_walk_path(user_walk), remote: true do %>
                <i class="fas fa-pen edit-icon ml-1"></i>
              <% end %>
            </span>
          </p>
        </div>
        <div class="mypastapp-status">
          <div class="badge badge-secondary badge-pill status"><%= user_walk.status %></div>
        </div>
      </div>
      <% end %>
  </div>
</div>


<!-- Modal AJAX by hand -->
<div id='user-walk-edit-content'></div>