config/routes.rb
Rails.application.routes.draw do
  get 'profiles/update'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get '/myapplications', to: 'pages#myapplications', as: :myapplications
  resources :positions,   only: [:create, :update, :show]
  resources :team,        only: [:create, :update]
  resources :walks,       only: [:create, :update, :destroy, :index, :show, :new] do
    resources :user_walks,  only: [:create]
  end
  resources :user_walks, only: [:destroy, :edit, :update]
  resources :skill_sets,  only: [:create, :update, :destroy]
  resources :skills,      only: [:create, :update]
  resources :profiles, only: [:update]
end

app/models/walk.rb
class Walk < ApplicationRecord
  belongs_to :team

  has_many :skill_sets, as: :skillable
  has_many :skills, through: :skill_sets

  validates :team, presence: true
  validates :purpose, presence: true


  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:description, :duration],
    associated_against: {
      team: [:location, :department, :name, :description]
    },
    using: {
      tsearch: { prefix: true }
    }
  pg_search_scope :search_by_location,
    associated_against: {
      team: [:location]
    },
    using: {
      tsearch: { prefix: true }
    }
  pg_search_scope :search_by_department,
    associated_against: {
      team: [:department]
    },
    using: {
      tsearch: { prefix: true }
    }
  pg_search_scope :search_by_duration,
    against: [:duration],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
before_action :set_walk, only: [:show, :update, :destroy]

  def index
    @user = current_user
    @walks = policy_scope(Walk)
    @walks = @walks.global_search(params[:query]) if params[:query].present?
    @walks = @walks.search_by_location(params[:location]) if params[:location].present?
    @walks = @walks.search_by_department(params[:department]) if params[:department].present?
    @walks = @walks.search_by_duration(params[:duration]) if params[:duration].present?
    @walks = ScoreService.new.order_score(@walks, @user)
  end

  def show
    @user_walk = UserWalk.new
    authorize @user_walk
  end

  def new
    # @walk = current_user.walks.new
    # authorize @walk
  end

  def create
    # @walk = current_user.walks.new(walk_params)
    # authorize @walk
    # if @walk.save
    #   redirect_to walk_path(@walk)
    # else
    #   render :new
    # end
  end

  def update
    # @walk.update(walk_params)
    # redirect_to walk_path(@walk)
  end

  def destroy
    # @walk.destroy if @walk.user_walks.empty?
  end

  private

  def walk_params
    params.require(:walk).permit(:description, :duration) #, :team)
  end

  def set_walk
    @walk = Walk.find(params[:id])
    authorize @walk
  end
end

app/views/walks/index.html.erb
  <!-- Searchbar -->
<div class="searchcontainer container-fluid p-0", id="searchbar-container">
  <div class="d-flex justify-content-around", id="searchbar">
  <%= form_tag( walks_path, {method: :get, class: 'form-inline'}) do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control search-field mr-2 w-70vw",
      placeholder: "Find a Walk"
    %>
    <%= select_tag(
      :location,
      options_for_select(Team.all.map{|t| t.location}.sort.uniq!, :location),
      include_blank: "Location",

      class: "form-control search-field mr-2 w-70vw" #select2

    ) %>

    <%= select_tag(
      :department,
      options_for_select(Team.all.map{|t| t.department}.sort.uniq!, :department),
      prompt: "Department",
      class: "form-control search-field mr-2 w-70vw"
    ) %>
    <%= select_tag(
      :duration,
      options_for_select(Walk.all.map{|w| w.duration}.sort.uniq!, :duration),
      include_blank: "Duration",
      class: "form-control search-field mr-2 w-70vw"
    ) %>
    <%= submit_tag "Search", class: "btn btn-search search-field" %>
  <% end %>
  </div>
</div>


<div class="container">
  <div class="cards-walks">
    <br>
      <% @walks.each do |walk| %>
        <%= link_to walk_path(walk) do %>
          <div class="card-dashboard">
            <div class="card-dashboard-image">
              <%= cl_image_tag walk.team.photo.key, width: 140, height: 140, crop: :fill, gravity: :faces if walk.team.photo.attached? %>
            </div>
            <div class="card-dashboard-infos">
              <h2><%= walk.title %></h2>
              <h3 class="duration">
                <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                data-placement="bottom" data-content="Suggested walk duration">
                  <i class="fas fa-calendar-week">
                  </i><%= walk.duration %>
                </span>
                <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="bottom" data-content="Purpose of the Walk">
                  <% if walk.purpose == "Recruitment"%>
                    <i class="ml-3 fas far fa-handshake">
                    </i> Recruitment
                  <% else %>
                    <i class="ml-3 fas fa-rocket">
                    </i> Discovery
                  <% end %>
                </span>
              <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="bottom" data-content="Team offering the Walk">
                <i class="ml-3 fas fa-users">
                </i><%= walk.team.name %>
              </span>
              <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="bottom" data-content="Location of the Walk">
                <i class="ml-3 fas fa-thumbtack">
                </i><%= walk.team.location %> </h3>
              </span>
              <p><%= walk.description.truncate(150) %> </p>

            </div>

            <!-- Progress bar 1 -->
            <div class="gauge-index walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                  data-placement="right" data-content="Matching score based on your skills and on the Walk's required skills">
              <div class="progress mx-auto" data-value=<%= "#{ScoreService.new.score(walk, @user)}" %>>
                <span class="progress-left">
                  <span class="progress-bar"></span>
                </span>
                <span class="progress-right">
                  <span class="progress-bar"></span>
                </span>
                <div class="progress-value w-100 h-100 rounded-circle d-flex align-items-center justify-content-center">
                  <p class="progress-font"><%= "#{ScoreService.new.score(walk, @user)}" %><sup class="small">%</sup></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <br>
  </div>
</div>

app/views/walks/show.html.erb
<div class="container p-4">

  <!-- LHS column with content -->
  <div class="card details-card p-4">
    <!-- Photo next to details -->
    <div class="d-flex justify-content-between">
      <div >
        <% if @walk.team.photo.attached?%>
           <%= cl_image_tag @walk.team.photo.key, width: 450, height: 325, crop: :fill %>
        <% else %>
          <%= cl_image_tag "", width: 400, height: 300, crop: :fill %>
        <% end %>
      </div>
      <div class= "mx-4 align-self-center flex-shrink-1" >
        <h2 class="book-title mb-3"><%= @walk.title %> </h2>
        <p><%= @walk.description %></p>
        <div class="d-flex mt-5">
          <div>
            <h3>Matching</h3>
            <p>Our matching scores take into account the skills you would like to acquire as well as the relevance of your skills via à vis the proposed walk.</p>
          </div>
          <div>

            <!-- gauge -->
            <div class="gauge-index ml-5 mr-3">
              <div class="progress mx-auto" data-value=<%= "#{ScoreService.new.score(@walk, current_user)}" %>>
                <span class="progress-left">
                  <span class="progress-bar"></span>
                </span>
                <span class="progress-right">
                  <span class="progress-bar"></span>
                </span>
                <div class="progress-value w-100 h-100 rounded-circle d-flex align-items-center justify-content-center">
                  <p class="progress-font"><%= "#{ScoreService.new.score(@walk, current_user)}" %><sup class="small">%</sup></p>
                </div>
              </div>
            </div>

          </div>
        </div>
       </div>
    </div>
  </div>
    <!-- Matching in words-->
    <!-- <div class="d-flex justify-content-between my-4">
      <div class="align-self-center flex-shrink-1">
        <h3>Matching</h3>
        <p>Our matching scores take into account the skills you would like to acquire \
      as well as the relevance of your skills via à vis the proposed walk.</p>
      </div>
    </div> -->

    <!-- Grid of team-members -->
  <div class="card details-card p-4 mb-3">
      <h3>Team</h3>
      <p><%= @walk.team.description %></p>

        <div class=" d-flex justify-content-around flex-wrap">
          <% @walk.team.positions.sort_by{|p| p.user.first_name}.sort_by{|p| p.role}.each do |member| %>
            <%= link_to position_path(member), remote: true do %>
              <div class="mt-3 p-0 card-mini-profile">
                <!-- <div> -->
                  <% if member.user.photo.attached?%>
                    <% if member.role == "manager" %>
                    <!-- <span class="walk-popover" data-container="body" data-toggle="popover" data-trigger="hover"
                data-placement="top" data-content="manager"> -->
                      <%= cl_image_tag member.user.photo.key, width: 85, height: 85, crop: :thumb, gravity: :face, class: "avatar-large-bordered"%>
                    <!-- </span> -->
                    <% else %>
                      <%= cl_image_tag member.user.photo.key, width: 85, height: 85, crop: :thumb, gravity: :face, class: "avatar-large" %>
                    <% end %>
                  <% else %>
                    <%= cl_image_tag "", width: 65, height: 65%>
                  <% end %>
                <!-- </div> -->
                <!-- <div class="ml-2 align-self-center"> -->
                  <% if member.role == 'manager'%>
                    <h6 class="my-1"> <strong> <%= member.user.first_name %> </strong> </h6>
                  <% else %>
                    <h6 class="my-1"> <%= member.user.first_name %> </h6>
                  <% end %>
                <!-- </div> -->
              </div>
            <% end %>
          <% end %>
        </div>
    </div>

    <!-- Button trigger modal -->
    <div class="d-flex justify-content-center">
      <button type="button" class="btn btn-letswalk px-4" data-toggle="modal" data-target="#applicationModal">
        Apply
      </button>
    </div>

  </div>
</div>

<!-- Modal apply -->
<div class="modal fade" id="applicationModal" tabindex="-1" role="dialog" aria-labelledby="applicationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="applicationModalLabel">Let's walk together!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@walk, @user_walk] do |f| %>
          <%= f.input :motivation, type: "text", label: "A few words about my motivation", class: "form-control", as: :text %>
          <div class="form-row p-3 booking-row">
          <div class="col">
            <%= f.input :start_date, type: "text", label: "Available from", class: "form-control", as: :string, input_html: { id: "range_start" } %>
          </div>
          <div class="col">
            <%= f.input :end_date, type: "text", label: "to", class: "form-control", as: :string, input_html: { id: "range_end" } %>
          </div>
          </div>
            <%= f.submit 'Send', class: 'btn btn-apply mb-2 modal-review-submit' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal AJAX by hand -->
<div id='member-content'></div>